version: '2'
services:

  server:
    image: java
    ports:
      - 8081:8080
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true

networks:
  default:
    external:
      name: mynetwork
