server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/springdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


# 配置slq打印日志
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl